import React, { useEffect, useState } from "react";
import { Loader, Card, FormField } from "../components";

const RenderCards = ({ data, title }) => {
  console.log(data);
  if (data?.length > 0) {
    return (
      data.map((post) => <Card key={post._id} {...post} />)
      );
  }
  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
  );
};
const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setallPosts] = useState(null);
  const [searchText, setsearchText] = useState("");
  const [searchTimeout, setsearchTimeout] = useState(null);
  const [searchedResult, setsearchedResult] = useState(null);

  const fetchPost = async () => {
     setLoading(true);
    try {
      const response = await fetch("https://ai-image-generator-7141.onrender.com/api/v1/post", {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      });
      console.log(response);
      if (response.ok) {
        const result = await response.json();
        setallPosts(result.data.reverse());
        console.log(result);
        console.log(result.data.reverse());
        console.log(allPosts);
      }
    } catch (error) {
      alert(error);
    } finally {
      setLoading(false);
    } 
    
  };

  useEffect(() => {
    fetchPost();
  }, []);

  const handelSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setsearchText(e.target.value);

    setsearchTimeout(
      setTimeout(() => {
        const searchResults = allPosts.filter(
          (item) =>
            item.name.toLowerCase().includes(searchText.toLowerCase()) ||
            item.prompt.toLowerCase().includes(searchText.toLowerCase())
        );
        setsearchedResult(searchResults);
      }, 500)
    );
  };
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w[500px]">
          Browse Through a collection of imaginative and visually stunning
          images generated by Suman AI
        </p>
      </div>
      <div className="mt-16">
        <FormField
          LabelName="Search Posts"
          type="text"
          name="text"
          placeholder="Search posts"
          value={searchText}
          handelChange={handelSearchChange}
        />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing results for{" "}
                <span className="text-[#222328]">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchedResult}
                  title="No search results found"
                />
              ) : (
                <RenderCards data={allPosts} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
